name: pomo_duck
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # route
  go_router: 13.0.0
  # bloc
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  # launcher icon
  flutter_launcher_icons: 0.13.1
  # notification
  flutter_local_notifications: 19.4.0
  # share & qr
  share_plus: 11.1.0
  qr_flutter: 4.1.0
  # google font
  google_fonts: 6.2.1
  # language
  easy_localization: 3.0.8
  easy_localization_loader: 2.0.2
  # hive storage
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_secure_storage: 9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  build_runner: 2.4.9
  flutter_gen_runner: 5.8.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/translations/

flutter_gen:
  output: lib/generated/assets

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

  assets:
    outputs:
      enabled: true
      style: dot-delimiter
      package_parameter_enabled: false
